package com.wakeup.zodiac.database;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DatabaseActivity extends SQLiteOpenHelper {

    private static String DB_NAME = null;
    private static final String DB_TABLE = "dbtable";
    public static final String KET_DB_FAVOURITE = "favourite";
    public static final String KEY_DB_CATEGORY = "category";
    public static final String KEY_DB_ID = "_id";
    public static final String KEY_DB_QUOTE = "quote";
    private static int VERSION = 0;
    public static final String name = "name";
    private SQLiteDatabase mDB = getWritableDatabase();

    static {
        DB_NAME = null;
        VERSION = 0;
        DB_NAME = null;
        VERSION = 0;
        DB_NAME = "AttitudeDB";
        VERSION = 1;
    }

    public DatabaseActivity(Context context) {
        super(context, DB_NAME, (SQLiteDatabase.CursorFactory) null, VERSION);
    }

    public Cursor getList(String word) {
        return this.mDB.query(DB_TABLE, new String[]{KEY_DB_ID, KEY_DB_CATEGORY, KEY_DB_QUOTE}, "category=?", new String[]{String.valueOf(word)}, null, null, null, null);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("create table dbtable ( _id integer primary key autoincrement , category text , quote text ,favourite text check( favourite IN ('Yes','No') ) NOT NULL DEFAULT 'No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Accusatory','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Apathetic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Ability','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Accepting','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Accommodating','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Active','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Ambitious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Articulate','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Assertive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'A','Attentive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Bitter','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Behavior','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Benevolent','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Bond','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Brave','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Bullseye','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Bravery','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Bullseye','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Blossom','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'B','Boldly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Charisma','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Cheerful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Civility','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Coherent','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Commitment','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Curiosity','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Creative','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Cordiality','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Conservative','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'C','Confidence','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Disdainful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Didactic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Derisive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Decent','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Dependable','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Desire','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Devoted','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Dignity','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Diplomatic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'D','Directed','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Earnest','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Empathetic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Encouragement','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Endurance','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Energetic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Enthusiastic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Equality','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Estimable','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Ethical','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'E','Euphoric','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Fanciful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Forthright','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Fairness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Faith','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Faithful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Feeling','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Flexible','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Forgiving','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Forte','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'F','Fortitude','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Gloomy','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Generosity','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Genial','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Genteel','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Gentle','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Genuine','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Goodness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Gracious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Gratitude','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'G','Guidance','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Haughty','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Happy','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Hard work','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Harmonious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Healing','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Helpfulness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Honesty','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Honorable','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Hopeful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'H','Humble','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Indignant','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Intimate','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Idealistic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Imaginative','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Impartiality','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Industrious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Innocence','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Innovative','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Inspirational','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'I','Instructive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Judgmental','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Jovial','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Jocular','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Jocund','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Jolly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Jovial','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Joyful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Jokingly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Joyously','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'J','Juggler','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kind','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kindness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kindred','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kinship','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Keenly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kiddingly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Knightly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Knowable','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kid-friendly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'K','Kilig','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Lyrical','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Laughter','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Leadership','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Legitimacy','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Loving','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Loyalty','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Lordly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Light-Hearted','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Liberal','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'L','Listener','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Mocking','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Morose','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Malicious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Mastery','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Merciful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Meritorious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Meticulous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Missionary','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Moderate','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'M','Motivational','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Nasty','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Naive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Nasal','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Natural','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Nauseous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Nearsighted','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Naughty','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Normal','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Nice','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'N','Noble','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Objective','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Optimistic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Obedience','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Observant','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Open-minded','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Opportunist','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Optimism','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Orderly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Oriented','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'O','Outspoken','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Potential','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Patriot','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Peaceful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Peacemaker','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Perceptive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Persistence','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Personable','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Polite','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Popular','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'P','Powerful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quizzical','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quality','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quick','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quiescent','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quintessential','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Queenly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quemeful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quietness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quirky','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Q','Quintessential','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Ribald','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Reverent','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Ridicule','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Rational','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Recognition','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Reflective','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Remorseful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Respectful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Responsible','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'R','Restraint','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Sarcastic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Sardonic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Special','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Selflessness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Sensitive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Successful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Supportive','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Sweet','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Sympathetic','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'S','Solitary','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Tactful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Talent','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Temperament','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Tenacious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Tendency','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Thankful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Thoughtfulness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Tolerant','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Trait','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'T','Tranquil','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Ultimate','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Understanding','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Unique','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','United','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Unaffectedly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Unbound','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Uncorrupted','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Undoubted','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Ungrudgingly','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'U','Useful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Volunteer','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Veracious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Veracity','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Versatile','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Vigilant','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Vigorous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Visible','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Vision','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Vivacious','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'V','Vocal','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Worrier','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Warm','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Watchful','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Wild','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Willingness','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Winner','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Wisdom','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Whimsical','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Worthwhile','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'W','Worthy','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'X','xanthous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'X','xiphophyllous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'X','xenial','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'X','xenodochial','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'X','xylotomous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Y','Yearning','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Y','Yielding','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Y','Yourself','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Y','Yonder','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Y','Young','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Z','Zeal','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Z','Zealous','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Z','Zest','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Z','Zippy','No') ");
        db.execSQL("insert into dbtable ( category,quote,favourite )  values ( 'Z','Zoetic','No') ");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }

}
